hack_blue_scroll_and_tell:
    resource: "@HackBlueScrollAndTellBundle/Resources/config/routing.yml"
    prefix: /

start:
    pattern:    /
    defaults: { _controller: HackBlueScrollAndTellBundle:Default:start }

story_create:
    pattern:    /story/create
    defaults: { _controller: HackBlueScrollAndTellBundle:Story:create }

story_create:
    pattern:    /story/edit
    defaults: { _controller: HackBlueScrollAndTellBundle:Story:edit }